<h2>Contact Us</h2>

<form action="<?php echo $block->getFormAction() ?>" method="post">

  <label for="name">Full Name:</label><br>
  <input type="text" id="name" name="name"><br>
  <label for="email">Email</label><br>
  <input type="text" id="email" name="email">
  <label for="description">What are you looking for ?</label><br>
  <input type="text" id="description" name="description"><br>
  <input type="submit" value="Send">
</form>