<h2>Contact Us</h2>

<form action="<?php echo $block->getFormAction() ?>" method="post">

  <label for="name">Full Name:</label><br>
  <input type="text" id="name" name="name"><br>
  <label for="email">Email</label><br>
  <input type="email" id="email" name="email">
  <label for="contact">Contact Number</label><br>
  <input type="number" id="contact" name="contact">
  <label for="description">What are you looking for ?</label><br>
  <textarea id="description" name="description" rows="4" cols="50"></textarea><br>
  <input type="submit" value="Send">
</form>